name: hundred_day
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  image_picker: ^1.0.4
  screenshot: ^2.1.0
  image_gallery_saver: ^2.0.3
  permission_handler: ^11.0.1
  flutter_staggered_grid_view:
  google_ml_kit: ^0.16.3
  translator: ^0.1.7
  google_maps_flutter:
  geocoding:
  geolocator:
  uuid: ^4.1.0
  http: ^0.13.6
  custom_info_window:
  path_provider: ^2.1.1
  # image_cropper:
  pdf:
  remove_background:
  shared_preferences: ^2.2.2
  math_expressions: ^2.4.0
  share_plus: ^7.2.1
  flutter_sms: ^2.3.3
  url_launcher: ^6.2.2
  app_settings: ^5.1.1
  flutter_local_notifications: ^16.3.0
  file_picker: ^6.1.1
  pdfx: ^2.5.0
  numberpicker: ^2.1.2
  workmanager: ^0.5.1
  pull_to_refresh: ^2.0.0
  zego_zim:
  zego_zimkit:
  zego_uikit_prebuilt_call: ^4.1.3
  record: ^5.0.4
  camera: ^0.10.5+9
  flutter_face_api: ^5.2.3
  path: ^1.8.3
  speech_to_text: ^6.5.1
  socket_io_client: ^2.0.3+1
 

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - asset/
    - asset/images/
    - asset/grid/
    - asset/style/
