List<Map<String, dynamic>> foodList = [
  {
    'name': 'Classic Burger',
    'price': 5.99,
    'description': 'Juicy beef patty with lettuce and cheese.',
    'category': 'Burgers',
  },
  {
    'name': 'Pepperoni Pizza',
    'price': 10.99,
    'description': 'Delicious pepperoni pizza with mozzarella cheese.',
    'category': 'Pizza',
  },
  {
    'name': 'Chizz Pizza',
    'price': 10.99,
    'description': 'Delicious pepperoni pizza with mozzarella cheese.',
    'category': 'Pizza',
  },
  {
    'name': 'Corn Pizza',
    'price': 10.99,
    'description': 'Delicious pepperoni pizza with mozzarella cheese.',
    'category': 'Pizza',
  },
  {
    'name': 'Sushi Combo',
    'price': 12.99,
    'description': 'Fresh sushi rolls with a variety of fillings.',
    'category': 'Sushi',
  },
  {
    'name': 'Garden Salad',
    'price': 7.99,
    'description': 'Healthy salad with mixed greens and vinaigrette.',
    'category': 'Salads',
  },
  {
    'name': 'Spaghetti with Meatballs',
    'price': 8.99,
    'description': 'Spaghetti with marinara sauce and meatballs.',
    'category': 'Pasta',
  },
   {
    'name': 's Meatballs',
    'price': 8.99,
    'description': 'Spaghetti with marinara sauce and meatballs.',
    'category': 'Pasta',
  },
  {
    'name': 'Beef Tacos',
    'price': 6.99,
    'description': 'Tasty tacos with seasoned beef and toppings.',
    'category': 'Tacos',
  },
  {
    'name': 'Sushi Deluxe',
    'price': 12.99,
    'description': 'Fresh sushi rolls with a variety of fillings.',
    'category': 'Sushi',
  },
  {
    'name': 'Chicken Wings',
    'price': 9.99,
    'description': 'Crispy chicken wings with a choice of sauces.',
    'category': 'Appetizers',
  },
  {
    'name': 'Vanilla Ice Cream',
    'price': 4.99,
    'description': 'Creamy vanilla ice cream with chocolate sauce.',
    'category': 'Desserts',
  },
   {
    'name': 'chocolate Ice Cream',
    'price': 4.99,
    'description': 'Creamy vanilla ice cream with chocolate sauce.',
    'category': 'Desserts',
  },
   {
    'name': 'Cake Ice Cream',
    'price': 4.99,
    'description': 'Creamy vanilla ice cream with chocolate sauce.',
    'category': 'Desserts',
  },
   {
    'name': 'Laddu',
    'price': 4.99,
    'description': 'Creamy vanilla ice cream with chocolate sauce.',
    'category': 'Desserts',
  },
  {
    'name': 'Ribeye Steak',
    'price': 15.99,
    'description': 'Grilled ribeye steak with a side of mashed potatoes.',
    'category': 'Steaks',
  },
];
